### ISSUE TITLE
EndoScene_list

### ISSUE THREAD

**Issue by ylHe** [CityU-AIM-Group/MPA-DA#1]
你好！方便提供一下EndoScene_list文件夹中的list文件么？非常感谢！

**Comment by nguyenlecong** [comment]
I also have the same wish.

**Comment by yanjiawei666** [comment]
你好！方便提供一下trian中的那些文件吗，比如dataset和data以及checkpoint等。还有就是model中是不是没有提供PST和DR这两个模块的代码。

**Comment by wh-isper** [comment]
> 你好！方便提供一下trian中的那些文件吗，比如dataset和data以及checkpoint等。还有就是model中是不是没有提供PST和DR这两个模块的代码。

这个代码有很大问题，很多论文的里的模块都没有，甚至还直接用目标域的标签来计算损失。

**Comment by cyang-cityu** [comment]
> 你好，EndoScene_list文件如下
[wce_train_fold3.txt](https://github.com/CityU-AIM-Group/MPA-DA/files/10397711/wce_train_fold3.txt)
[wce_train_fold4.txt](https://github.com/CityU-AIM-Group/MPA-DA/files/10397712/wce_train_fold4.txt)
[wce_test_fold1.txt](https://github.com/CityU-AIM-Group/MPA-DA/files/10397705/wce_test_fold1.txt)
[wce_test_fold2.txt](https://github.com/CityU-AIM-Group/MPA-DA/files/10397706/wce_test_fold2.txt)
[wce_test_fold3.txt](https://github.com/CityU-AIM-Group/MPA-DA/files/10397707/wce_test_fold3.txt)
[wce_test_fold4.txt](https://github.com/CityU-AIM-Group/MPA-DA/files/10397708/wce_test_fold4.txt)
[wce_train_fold1.txt](https://github.com/CityU-AIM-Group/MPA-DA/files/10397709/wce_train_fold1.txt)
[wce_train_fold2.txt](https://github.com/CityU-AIM-Group/MPA-DA/files/10397710/wce_train_fold2.txt)

**Comment by cyang-cityu** [comment]
> 你好，论文里其他模块我最近更新，你说提到的直接用目标域的标签来计算损失，应该指的是用伪标签计算，而并不是真实标签

**Comment by cyang-cityu** [comment]
> 你好！方便提供一下EndoScene_list文件夹中的list文件么？非常感谢！

你好，EndoScene_list文件如下
[test.txt](https://github.com/CityU-AIM-Group/MPA-DA/files/10397897/test.txt)
[train.txt](https://github.com/CityU-AIM-Group/MPA-DA/files/10397898/train.txt)
