### ISSUE TITLE
代码与论文不一致？

### ISSUE THREAD

**Issue by lllzzzrrr** [CityU-AIM-Group/MPA-DA#2]
作者您好！我在阅读代码的时候发现代码与论文出入很大。
1.论文中总的损失有很多种，Dice loss、MaxSquare loss、uncertainty guided self-training loss等等，但是代码中只有Dice Loss
2.论文中的设定是目标域是未标注的，通过计算Jensen–Shannon divergence和伪标签来计算目标域的分割损失。但是实际代码中直接使用了目标域的标签计算Dice loss????

**Comment by lllzzzrrr** [comment]
@cyang-cityu

**Comment by cyang-cityu** [comment]
你好，文中使用的是Dice loss和uncertainty guided self-training loss，并没有使用MaxSquare loss，其余部分我最近更新，实际代码中并没有直接使用了目标域的标签计算Dice loss，而是伪标签计算的。
![image](https://user-images.githubusercontent.com/54945895/211963863-38bba833-9dd7-4a50-9940-5662d76d2ab0.png)

**Comment by yanjiawei666** [comment]
前辈您好，多有打扰，请问您啥时候更新其余部分呢
